# Generated by: Neurodocker version 0.7.0+0.gdc97516.dirty
# Latest release: Neurodocker version 0.8.0
# Timestamp: 2022/03/29 17:10:18 UTC
# 
# Thank you for using Neurodocker. If you discover any issues
# or ways to improve this software, please submit an issue or
# pull request on our GitHub repository:
# 
#     https://github.com/ReproNim/neurodocker

FROM debian:stretch-slim

USER root

ARG DEBIAN_FRONTEND="noninteractive"

ENV LANG="en_US.UTF-8" \
    LC_ALL="en_US.UTF-8" \
    ND_ENTRYPOINT="/neurodocker/startup.sh"
RUN export ND_ENTRYPOINT="/neurodocker/startup.sh" \
    && apt-get update -qq \
    && apt-get install -y -q --no-install-recommends \
           apt-utils \
           bzip2 \
           ca-certificates \
           curl \
           locales \
           unzip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen \
    && dpkg-reconfigure --frontend=noninteractive locales \
    && update-locale LANG="en_US.UTF-8" \
    && chmod 777 /opt && chmod a+s /opt \
    && mkdir -p /neurodocker \
    && if [ ! -f "$ND_ENTRYPOINT" ]; then \
         echo '#!/usr/bin/env bash' >> "$ND_ENTRYPOINT" \
    &&   echo 'set -e' >> "$ND_ENTRYPOINT" \
    &&   echo 'export USER="${USER:=`whoami`}"' >> "$ND_ENTRYPOINT" \
    &&   echo 'if [ -n "$1" ]; then "$@"; else /usr/bin/env bash; fi' >> "$ND_ENTRYPOINT"; \
    fi \
    && chmod -R 777 /neurodocker && chmod a+s /neurodocker

ENTRYPOINT ["/neurodocker/startup.sh"]

LABEL version="2.1.1dev"

RUN apt-get update -qq \
    && apt-get install -y -q --no-install-recommends \
           build-essential libz-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir /input /output

RUN chmod -R 777 /output

RUN test "$(getent passwd laynii)" || useradd --no-user-group --create-home --shell /bin/bash laynii
USER laynii

COPY ["dep", "/home/laynii/dep"]

COPY ["src", "/home/laynii/src"]

COPY ["Makefile", "/home/laynii/"]

WORKDIR /home/laynii/

RUN make all

RUN sed -i '$iPATH=/home/laynii/:$PATH' $ND_ENTRYPOINT

RUN echo '{ \
    \n  "pkg_manager": "apt", \
    \n  "instructions": [ \
    \n    [ \
    \n      "base", \
    \n      "debian:stretch-slim" \
    \n    ], \
    \n    [ \
    \n      "label", \
    \n      { \
    \n        "version": "2.1.1dev" \
    \n      } \
    \n    ], \
    \n    [ \
    \n      "install", \
    \n      [ \
    \n        "build-essential libz-dev" \
    \n      ] \
    \n    ], \
    \n    [ \
    \n      "run", \
    \n      "mkdir /input /output" \
    \n    ], \
    \n    [ \
    \n      "run", \
    \n      "chmod -R 777 /output" \
    \n    ], \
    \n    [ \
    \n      "user", \
    \n      "laynii" \
    \n    ], \
    \n    [ \
    \n      "copy", \
    \n      [ \
    \n        "dep", \
    \n        "/home/laynii/dep" \
    \n      ] \
    \n    ], \
    \n    [ \
    \n      "copy", \
    \n      [ \
    \n        "src", \
    \n        "/home/laynii/src" \
    \n      ] \
    \n    ], \
    \n    [ \
    \n      "copy", \
    \n      [ \
    \n        "Makefile", \
    \n        "/home/laynii/" \
    \n      ] \
    \n    ], \
    \n    [ \
    \n      "workdir", \
    \n      "/home/laynii/" \
    \n    ], \
    \n    [ \
    \n      "run", \
    \n      "make all" \
    \n    ], \
    \n    [ \
    \n      "add_to_entrypoint", \
    \n      "PATH=/home/laynii/:$PATH" \
    \n    ] \
    \n  ] \
    \n}' > /neurodocker/neurodocker_specs.json
