
#include "../dep/laynii_lib.h"


int show_help(void) {
    printf(
    "LN2_CIRCSHIFT: Circularly shifts voxels along one axis. Useful for wraps\n"
    "               where e.g. occipital pole is wrapped to anterior slices\n"
    "               but is not overlapping with frontal brain tissue."
    "\n"
    "Usage:\n"
    "    LN2_CIRCSHIFT -input data_file.nii -shift_neg 10 -axis 2 \n"
    "\n"
    "Options:\n"
    "    -help      : Show this help.\n"
    "    -input     : Input multi-tissue segmentation image (2D or 3D).\n"
    "    -axis      : Axis of the projection. x=1, y=2, z=4. Default is '3'.\n"
    "                 Projections over each axis can be generated by using '0'.\n"
    "    -shift_pos : Number of slices that will be circular shifted forwards\n"
    "                 along chosen axis. Default is '10'.\n"
    "    -shift_neg : Number of slices that will be circular shifted backwards\n"
    "                  along chosen axis. Default is '10'.\n"
    "    -output    : (Optional) Output filename, including .nii or\n"
    "                 .nii.gz, and path if needed. Overwrites existing files.\n"
    "\n"
    "\n");
    return 0;
}

int main(int argc, char * argv[]) {
    char *fin = NULL, *fout = NULL;
    int64_t ac, axis = 3, shift = 10;

    // Process user options
    if (argc < 2) return show_help();
    for (ac = 1; ac < argc; ac++) {
        if (!strncmp(argv[ac], "-h", 2)) {
            return show_help();
        } else if (!strcmp(argv[ac], "-input")) {
            if (++ac >= argc) {
                fprintf(stderr, "** missing argument for -input\n");
                return 1;
            }
            fin = argv[ac];
            fout = argv[ac];
        } else if (!strcmp(argv[ac], "-axis")) {
            if (++ac >= argc) {
                fprintf(stderr, "** missing argument for -axis\n");
            } else {
                axis = std::atoll(argv[ac]);
            }
        } else if (!strcmp(argv[ac], "-shift_pos")) {
            if (++ac >= argc) {
                fprintf(stderr, "** missing argument for -shift_pos\n");
            } else {
                shift = std::atoll(argv[ac]);
            }
        } else if (!strcmp(argv[ac], "-shift_neg")) {
            if (++ac >= argc) {
                fprintf(stderr, "** missing argument for -shift_neg\n");
            } else {
                shift = -std::atoll(argv[ac]);
            }
        } else if (!strcmp(argv[ac], "-output")) {
            if (++ac >= argc) {
                fprintf(stderr, "** missing argument for -output\n");
                return 1;
            }
            fout = argv[ac];
        }
    }

    if (!fin) {
        fprintf(stderr, "** missing option '-input'\n");
        return 1;
    }
    // Read input dataset
    nifti_image * nii1 = nifti_image_read(fin, 1);
    if (!nii1) {
        fprintf(stderr, "** failed to read NIfTI image from '%s'\n", fin);
        return 2;
    }

    // Read input dataset, including data
    if ( axis < 0 || axis > 3) {
        fprintf(stderr, "Incorrect axis value. Please choose between 0, 1, 2, 3.\n");
        return 2;
    }

    log_welcome("LN2_CIRCSHIFT");
    log_nifti_descriptives(nii1);

    // Get dimensions of input
    const int64_t size_x = static_cast<int64_t>(nii1->nx);
    const int64_t size_y = static_cast<int64_t>(nii1->ny);
    const int64_t size_z = static_cast<int64_t>(nii1->nz);
    const int64_t size_time =  static_cast<int64_t>(nii1->nt);
    const int64_t nr_voxels = size_z * size_y * size_x * size_time;

    // ========================================================================
    // Fix data type issues
    // ========================================================================

    nifti_image* nii_input = copy_nifti_as_int16(nii1);
    int16_t* nii_input_data = static_cast<int16_t*>(nii_input->data);

    nifti_image* nii_output = copy_nifti_as_int16(nii1);
    int16_t* nii_output_data = static_cast<int16_t*>(nii_output->data);

    // ========================================================================
    // Circular shift
    // ========================================================================
    if (axis == 1) {
        cout << "  Circular shifting over 1st axis..." << endl;

        int64_t ix, iy, iz, it, j;
        for (int64_t i = 0; i != nr_voxels; ++i) {
            tie(ix, iy, iz, it) = ind2sub_4D_64(i, size_x, size_y, size_z);

            // Compute circular shifted index
            int64_t jx = ((ix + shift) % size_x + size_x) % size_x;
            j = sub2ind_4D_64(jx, iy, iz, it, size_x, size_y, size_z);

            // Copy data
            *(nii_output_data + j) = *(nii_input_data + i);
        }

        cout << "  Saving output..." << endl;
        save_output_nifti(fout, "circshift-x", nii_output, true);
    }

    else if (axis == 2) {
        cout << "  Circular shifting over 2nd axis..." << endl;

        int64_t ix, iy, iz, it, j;
        for (int64_t i = 0; i != nr_voxels; ++i) {
            tie(ix, iy, iz, it) = ind2sub_4D_64(i, size_x, size_y, size_z);

            // Compute circular shifted index
            int64_t jy = ((iy + shift) % size_y + size_y) % size_y;
            j = sub2ind_4D_64(ix, jy, iz, it, size_x, size_y, size_z);

            // Copy data
            *(nii_output_data + j) = *(nii_input_data + i);
        }

        cout << "  Saving output..." << endl;
        save_output_nifti(fout, "circshift-y", nii_output, true);
    }

    else if (axis == 3) {
        cout << "  Circular shifting over 3rd axis..." << endl;

        int64_t ix, iy, iz, it, j;
        for (int64_t i = 0; i != nr_voxels; ++i) {
            tie(ix, iy, iz, it) = ind2sub_4D_64(i, size_x, size_y, size_z);

            // Compute circular shifted index
            int64_t jz = ((iz + shift) % size_z + size_z) % size_z;
            j = sub2ind_4D_64(ix, iy, jz, it, size_x, size_y, size_z);

            // Copy data
            *(nii_output_data + j) = *(nii_input_data + i);
        }

        cout << "  Saving output..." << endl;
        save_output_nifti(fout, "circshift-z", nii_output, true);
    }

    cout << "\n  Finished." << endl;
    return 0;
}